-- ItemTODO status enum
CREATE TYPE todo_status AS ENUM ('OPEN', 'CLOSED');

-- TABLE

CREATE TABLE IF NOT EXISTS todo (
    id SERIAL PRIMARY KEY,
    cid INTEGER NOT NULL, --creator id
    ctime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title VARCHAR(127) NOT NULL,
    status todo_status NOT NULL DEFAULT 'OPEN'
);

ALTER SEQUENCE todo_id_seq RESTART WITH 1000;